/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/4FKbWBGCk33
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { ResponsiveLine } from "@nivo/line"
import { Card } from "@/components/ui/card"

export function Example() {
  return (
    <div className="flex flex-col min-h-screen items-center justify-center py-12 space-y-4 md:space-y-8">
      <div className="flex flex-col items-center space-y-2">
        <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Investle</h1>
        <p className="mx-auto max-w-[600px] text-center text-gray-500 md:text-xl/relaxed dark:text-gray-400">
          Guess the company of the day from the S&P 500. Enter the ticker symbol below to make your guess.
        </p>
      </div>
      <div className="flex items-center gap-4">
        <Input className="w-[300px] shadow" placeholder="Enter a ticker symbol or company name" type="text" />
        <Button size="lg">Make a guess</Button>
      </div>
      <Card className="w-full max-w-3xl">
        <div className="p-4 grid gap-4">
          <div className="flex flex-col items-center gap-2">
            <div className="flex items-center gap-2 text-2xl font-semibold">
              <img
                alt="Company logo"
                className="rounded-lg aspect-[1/1] overflow-hidden object-cover object-center mr-2"
                height="40"
                src="/placeholder.svg"
                width="40"
              />
              <span>Microsoft Corporation</span>
              <span>(MSFT)</span>
            </div>
            <CurvedlineChart className="w-full aspect-[2/1]" />
          </div>
          <div className="grid gap-2 text-sm">
            <div className="grid grid-cols-2 items-center gap-2">
              <div>Market Cap</div>
              <div>$2.5T</div>
            </div>
            <div className="grid grid-cols-2 items-center gap-2">
              <div>Sector</div>
              <div>Technology</div>
            </div>
            <div className="grid grid-cols-2 items-center gap-2">
              <div>Employees</div>
              <div>181,000</div>
            </div>
          </div>
        </div>
      </Card>
    </div>
  )
}


function CurvedlineChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
          min: 0,
          max: "auto",
        }}
        curve="monotoneX"
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}
